/*
 * This file is generated by jOOQ.
*/
package org.campus.partner.pojo.po.mysql.tables.records;


import java.util.Date;

import javax.annotation.Generated;

import org.campus.partner.pojo.po.mysql.tables.CompanionRoom;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompanionRoomRecord extends UpdatableRecordImpl<CompanionRoomRecord> implements Record16<Long, byte[], Integer, Integer, Integer, String, Date, String, String, String, String, String, Integer, Date, Date, String> {

    private static final long serialVersionUID = 401231061;

    /**
     * Setter for <code>campus_partner.companion_room.id</code>. 自增主键id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.id</code>. 自增主键id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>campus_partner.companion_room.object_id</code>. 全局唯一id
     */
    public void setObjectId(byte... value) {
        set(1, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.object_id</code>. 全局唯一id
     */
    public byte[] getObjectId() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>campus_partner.companion_room.max_member_num</code>. 房间最大人数
     */
    public void setMaxMemberNum(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.max_member_num</code>. 房间最大人数
     */
    public Integer getMaxMemberNum() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>campus_partner.companion_room.status</code>. 房间状态：0-关闭，1-开放
     */
    public void setStatus(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.status</code>. 房间状态：0-关闭，1-开放
     */
    public Integer getStatus() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>campus_partner.companion_room.contact_type</code>. 进入房间需要留下的联系方式，0：QQ，1：微信，2：电话
     */
    public void setContactType(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.contact_type</code>. 进入房间需要留下的联系方式，0：QQ，1：微信，2：电话
     */
    public Integer getContactType() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>campus_partner.companion_room.comment</code>. 结伴备注信息
     */
    public void setComment(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.comment</code>. 结伴备注信息
     */
    public String getComment() {
        return (String) get(5);
    }

    /**
     * Setter for <code>campus_partner.companion_room.post_time</code>. 结伴的时间
     */
    public void setPostTime(Date value) {
        set(6, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.post_time</code>. 结伴的时间
     */
    public Date getPostTime() {
        return (Date) get(6);
    }

    /**
     * Setter for <code>campus_partner.companion_room.owner_id</code>. 房主 ID
     */
    public void setOwnerId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.owner_id</code>. 房主 ID
     */
    public String getOwnerId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>campus_partner.companion_room.owner_phone</code>. 房主电话
     */
    public void setOwnerPhone(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.owner_phone</code>. 房主电话
     */
    public String getOwnerPhone() {
        return (String) get(8);
    }

    /**
     * Setter for <code>campus_partner.companion_room.content</code>. 房间信息
     */
    public void setContent(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.content</code>. 房间信息
     */
    public String getContent() {
        return (String) get(9);
    }

    /**
     * Setter for <code>campus_partner.companion_room.start_location</code>. 结伴的起点（用于出现结伴)
     */
    public void setStartLocation(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.start_location</code>. 结伴的起点（用于出现结伴)
     */
    public String getStartLocation() {
        return (String) get(10);
    }

    /**
     * Setter for <code>campus_partner.companion_room.end_location</code>. 结伴的地点
     */
    public void setEndLocation(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.end_location</code>. 结伴的地点
     */
    public String getEndLocation() {
        return (String) get(11);
    }

    /**
     * Setter for <code>campus_partner.companion_room.tag</code>. 结伴类型 ID，0：运动，1：旅行， 2：出行，3：学习
     */
    public void setTag(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.tag</code>. 结伴类型 ID，0：运动，1：旅行， 2：出行，3：学习
     */
    public Integer getTag() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>campus_partner.companion_room.created_datetime</code>. 记录创建时间
     */
    public void setCreatedDatetime(Date value) {
        set(13, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.created_datetime</code>. 记录创建时间
     */
    public Date getCreatedDatetime() {
        return (Date) get(13);
    }

    /**
     * Setter for <code>campus_partner.companion_room.modified_datetime</code>. 记录更新时间
     */
    public void setModifiedDatetime(Date value) {
        set(14, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.modified_datetime</code>. 记录更新时间
     */
    public Date getModifiedDatetime() {
        return (Date) get(14);
    }

    /**
     * Setter for <code>campus_partner.companion_room.search_text</code>.
     */
    public void setSearchText(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>campus_partner.companion_room.search_text</code>.
     */
    public String getSearchText() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, byte[], Integer, Integer, Integer, String, Date, String, String, String, String, String, Integer, Date, Date, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, byte[], Integer, Integer, Integer, String, Date, String, String, String, String, String, Integer, Date, Date, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return CompanionRoom.COMPANION_ROOM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field2() {
        return CompanionRoom.COMPANION_ROOM.OBJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CompanionRoom.COMPANION_ROOM.MAX_MEMBER_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return CompanionRoom.COMPANION_ROOM.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return CompanionRoom.COMPANION_ROOM.CONTACT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CompanionRoom.COMPANION_ROOM.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field7() {
        return CompanionRoom.COMPANION_ROOM.POST_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return CompanionRoom.COMPANION_ROOM.OWNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return CompanionRoom.COMPANION_ROOM.OWNER_PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return CompanionRoom.COMPANION_ROOM.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return CompanionRoom.COMPANION_ROOM.START_LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return CompanionRoom.COMPANION_ROOM.END_LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return CompanionRoom.COMPANION_ROOM.TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field14() {
        return CompanionRoom.COMPANION_ROOM.CREATED_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field15() {
        return CompanionRoom.COMPANION_ROOM.MODIFIED_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return CompanionRoom.COMPANION_ROOM.SEARCH_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value2() {
        return getObjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMaxMemberNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getContactType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value7() {
        return getPostTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getOwnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getOwnerPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getStartLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getEndLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value14() {
        return getCreatedDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value15() {
        return getModifiedDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getSearchText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value2(byte... value) {
        setObjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value3(Integer value) {
        setMaxMemberNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value4(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value5(Integer value) {
        setContactType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value6(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value7(Date value) {
        setPostTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value8(String value) {
        setOwnerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value9(String value) {
        setOwnerPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value10(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value11(String value) {
        setStartLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value12(String value) {
        setEndLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value13(Integer value) {
        setTag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value14(Date value) {
        setCreatedDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value15(Date value) {
        setModifiedDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord value16(String value) {
        setSearchText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CompanionRoomRecord values(Long value1, byte[] value2, Integer value3, Integer value4, Integer value5, String value6, Date value7, String value8, String value9, String value10, String value11, String value12, Integer value13, Date value14, Date value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CompanionRoomRecord
     */
    public CompanionRoomRecord() {
        super(CompanionRoom.COMPANION_ROOM);
    }

    /**
     * Create a detached, initialised CompanionRoomRecord
     */
    public CompanionRoomRecord(Long id, byte[] objectId, Integer maxMemberNum, Integer status, Integer contactType, String comment, Date postTime, String ownerId, String ownerPhone, String content, String startLocation, String endLocation, Integer tag, Date createdDatetime, Date modifiedDatetime, String searchText) {
        super(CompanionRoom.COMPANION_ROOM);

        set(0, id);
        set(1, objectId);
        set(2, maxMemberNum);
        set(3, status);
        set(4, contactType);
        set(5, comment);
        set(6, postTime);
        set(7, ownerId);
        set(8, ownerPhone);
        set(9, content);
        set(10, startLocation);
        set(11, endLocation);
        set(12, tag);
        set(13, createdDatetime);
        set(14, modifiedDatetime);
        set(15, searchText);
    }
}
