/*
 * This file is generated by jOOQ.
*/
package org.campus.partner.pojo.po.mysql.tables.records;


import java.util.Date;

import javax.annotation.Generated;

import org.campus.partner.pojo.po.mysql.tables.RoomMember;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomMemberRecord extends UpdatableRecordImpl<RoomMemberRecord> implements Record6<Long, byte[], byte[], byte[], Date, Date> {

    private static final long serialVersionUID = -610145696;

    /**
     * Setter for <code>campus_partner.room_member.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>campus_partner.room_member.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>campus_partner.room_member.object_id</code>.
     */
    public void setObjectId(byte... value) {
        set(1, value);
    }

    /**
     * Getter for <code>campus_partner.room_member.object_id</code>.
     */
    public byte[] getObjectId() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>campus_partner.room_member.user_id</code>.
     */
    public void setUserId(byte... value) {
        set(2, value);
    }

    /**
     * Getter for <code>campus_partner.room_member.user_id</code>.
     */
    public byte[] getUserId() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>campus_partner.room_member.room_id</code>.
     */
    public void setRoomId(byte... value) {
        set(3, value);
    }

    /**
     * Getter for <code>campus_partner.room_member.room_id</code>.
     */
    public byte[] getRoomId() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>campus_partner.room_member.createdDatetime</code>.
     */
    public void setCreateddatetime(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>campus_partner.room_member.createdDatetime</code>.
     */
    public Date getCreateddatetime() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>campus_partner.room_member.modifiedDatetime</code>.
     */
    public void setModifieddatetime(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>campus_partner.room_member.modifiedDatetime</code>.
     */
    public Date getModifieddatetime() {
        return (Date) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, byte[], byte[], byte[], Date, Date> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, byte[], byte[], byte[], Date, Date> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return RoomMember.ROOM_MEMBER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field2() {
        return RoomMember.ROOM_MEMBER.OBJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field3() {
        return RoomMember.ROOM_MEMBER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field4() {
        return RoomMember.ROOM_MEMBER.ROOM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return RoomMember.ROOM_MEMBER.CREATEDDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return RoomMember.ROOM_MEMBER.MODIFIEDDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value2() {
        return getObjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value4() {
        return getRoomId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getCreateddatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getModifieddatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomMemberRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomMemberRecord value2(byte... value) {
        setObjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomMemberRecord value3(byte... value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomMemberRecord value4(byte... value) {
        setRoomId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomMemberRecord value5(Date value) {
        setCreateddatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomMemberRecord value6(Date value) {
        setModifieddatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomMemberRecord values(Long value1, byte[] value2, byte[] value3, byte[] value4, Date value5, Date value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoomMemberRecord
     */
    public RoomMemberRecord() {
        super(RoomMember.ROOM_MEMBER);
    }

    /**
     * Create a detached, initialised RoomMemberRecord
     */
    public RoomMemberRecord(Long id, byte[] objectId, byte[] userId, byte[] roomId, Date createddatetime, Date modifieddatetime) {
        super(RoomMember.ROOM_MEMBER);

        set(0, id);
        set(1, objectId);
        set(2, userId);
        set(3, roomId);
        set(4, createddatetime);
        set(5, modifieddatetime);
    }
}
