/*
 * This file is generated by jOOQ.
*/
package org.campus.partner.pojo.po.mysql.tables.records;


import java.util.Date;

import javax.annotation.Generated;

import org.campus.partner.pojo.po.mysql.tables.Subscribe;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubscribeRecord extends UpdatableRecordImpl<SubscribeRecord> implements Record11<Long, byte[], String, String, String, String, String, Integer, Date, Date, Date> {

    private static final long serialVersionUID = 1500149214;

    /**
     * Setter for <code>campus_partner.subscribe.id</code>. 自增主键id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>campus_partner.subscribe.id</code>. 自增主键id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>campus_partner.subscribe.object_id</code>. 全局唯一id
     */
    public void setObjectId(byte... value) {
        set(1, value);
    }

    /**
     * Getter for <code>campus_partner.subscribe.object_id</code>. 全局唯一id
     */
    public byte[] getObjectId() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>campus_partner.subscribe.user_id</code>. 发布结伴信息的用户 ID
     */
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>campus_partner.subscribe.user_id</code>. 发布结伴信息的用户 ID
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>campus_partner.subscribe.user_phone</code>. 订阅消息的用户的电话，用户消息推送
     */
    public void setUserPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>campus_partner.subscribe.user_phone</code>. 订阅消息的用户的电话，用户消息推送
     */
    public String getUserPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>campus_partner.subscribe.content</code>. 订阅的结伴消息的主要内容
     */
    public void setContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>campus_partner.subscribe.content</code>. 订阅的结伴消息的主要内容
     */
    public String getContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>campus_partner.subscribe.start_location</code>. 订阅的结伴消息的起点（用于出行结伴)
     */
    public void setStartLocation(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>campus_partner.subscribe.start_location</code>. 订阅的结伴消息的起点（用于出行结伴)
     */
    public String getStartLocation() {
        return (String) get(5);
    }

    /**
     * Setter for <code>campus_partner.subscribe.end_location</code>. 订阅的结伴消息的地点
     */
    public void setEndLocation(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>campus_partner.subscribe.end_location</code>. 订阅的结伴消息的地点
     */
    public String getEndLocation() {
        return (String) get(6);
    }

    /**
     * Setter for <code>campus_partner.subscribe.subscribe_tag</code>. 订阅的结伴消息类型 ID，0：运动，1：旅行， 2：出行，3：学习
     */
    public void setSubscribeTag(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>campus_partner.subscribe.subscribe_tag</code>. 订阅的结伴消息类型 ID，0：运动，1：旅行， 2：出行，3：学习
     */
    public Integer getSubscribeTag() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>campus_partner.subscribe.subscribe_end_datetime</code>. 订阅消息对于的截止日期
     */
    public void setSubscribeEndDatetime(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>campus_partner.subscribe.subscribe_end_datetime</code>. 订阅消息对于的截止日期
     */
    public Date getSubscribeEndDatetime() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>campus_partner.subscribe.created_datetime</code>. 记录创建时间
     */
    public void setCreatedDatetime(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>campus_partner.subscribe.created_datetime</code>. 记录创建时间
     */
    public Date getCreatedDatetime() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>campus_partner.subscribe.modified_datetime</code>. 记录更新时间
     */
    public void setModifiedDatetime(Date value) {
        set(10, value);
    }

    /**
     * Getter for <code>campus_partner.subscribe.modified_datetime</code>. 记录更新时间
     */
    public Date getModifiedDatetime() {
        return (Date) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, byte[], String, String, String, String, String, Integer, Date, Date, Date> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, byte[], String, String, String, String, String, Integer, Date, Date, Date> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Subscribe.SUBSCRIBE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field2() {
        return Subscribe.SUBSCRIBE.OBJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Subscribe.SUBSCRIBE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Subscribe.SUBSCRIBE.USER_PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Subscribe.SUBSCRIBE.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Subscribe.SUBSCRIBE.START_LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Subscribe.SUBSCRIBE.END_LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Subscribe.SUBSCRIBE.SUBSCRIBE_TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field9() {
        return Subscribe.SUBSCRIBE.SUBSCRIBE_END_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field10() {
        return Subscribe.SUBSCRIBE.CREATED_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field11() {
        return Subscribe.SUBSCRIBE.MODIFIED_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value2() {
        return getObjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUserPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getStartLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEndLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getSubscribeTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value9() {
        return getSubscribeEndDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value10() {
        return getCreatedDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value11() {
        return getModifiedDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubscribeRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubscribeRecord value2(byte... value) {
        setObjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubscribeRecord value3(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubscribeRecord value4(String value) {
        setUserPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubscribeRecord value5(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubscribeRecord value6(String value) {
        setStartLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubscribeRecord value7(String value) {
        setEndLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubscribeRecord value8(Integer value) {
        setSubscribeTag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubscribeRecord value9(Date value) {
        setSubscribeEndDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubscribeRecord value10(Date value) {
        setCreatedDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubscribeRecord value11(Date value) {
        setModifiedDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubscribeRecord values(Long value1, byte[] value2, String value3, String value4, String value5, String value6, String value7, Integer value8, Date value9, Date value10, Date value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubscribeRecord
     */
    public SubscribeRecord() {
        super(Subscribe.SUBSCRIBE);
    }

    /**
     * Create a detached, initialised SubscribeRecord
     */
    public SubscribeRecord(Long id, byte[] objectId, String userId, String userPhone, String content, String startLocation, String endLocation, Integer subscribeTag, Date subscribeEndDatetime, Date createdDatetime, Date modifiedDatetime) {
        super(Subscribe.SUBSCRIBE);

        set(0, id);
        set(1, objectId);
        set(2, userId);
        set(3, userPhone);
        set(4, content);
        set(5, startLocation);
        set(6, endLocation);
        set(7, subscribeTag);
        set(8, subscribeEndDatetime);
        set(9, createdDatetime);
        set(10, modifiedDatetime);
    }
}
