/*
 * This file is generated by jOOQ.
*/
package org.campus.partner.pojo.po.mysql.tables.records;


import java.util.Date;

import javax.annotation.Generated;

import org.campus.partner.pojo.po.mysql.tables.User;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record16<Long, byte[], Date, String, Integer, String, String, String, String, String, Integer, String, String, Integer, String, String> {

    private static final long serialVersionUID = -699867170;

    /**
     * Setter for <code>campus_partner.user.id</code>. 自增主键id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>campus_partner.user.id</code>. 自增主键id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>campus_partner.user.object_id</code>. 用户全局 ID
     */
    public void setObjectId(byte... value) {
        set(1, value);
    }

    /**
     * Getter for <code>campus_partner.user.object_id</code>. 用户全局 ID
     */
    public byte[] getObjectId() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>campus_partner.user.auth_datetime</code>. 用户认证时间
     */
    public void setAuthDatetime(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>campus_partner.user.auth_datetime</code>. 用户认证时间
     */
    public Date getAuthDatetime() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>campus_partner.user.auth_id</code>. 用户认证 ID，取学号为 ID
     */
    public void setAuthId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>campus_partner.user.auth_id</code>. 用户认证 ID，取学号为 ID
     */
    public String getAuthId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>campus_partner.user.auth_type</code>. 认证类型
     */
    public void setAuthType(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>campus_partner.user.auth_type</code>. 认证类型
     */
    public Integer getAuthType() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>campus_partner.user.qq</code>. QQ
     */
    public void setQq(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>campus_partner.user.qq</code>. QQ
     */
    public String getQq() {
        return (String) get(5);
    }

    /**
     * Setter for <code>campus_partner.user.wechat</code>. 微信
     */
    public void setWechat(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>campus_partner.user.wechat</code>. 微信
     */
    public String getWechat() {
        return (String) get(6);
    }

    /**
     * Setter for <code>campus_partner.user.phone</code>. 电话
     */
    public void setPhone(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>campus_partner.user.phone</code>. 电话
     */
    public String getPhone() {
        return (String) get(7);
    }

    /**
     * Setter for <code>campus_partner.user.avatar_url</code>. 头像 Url
     */
    public void setAvatarUrl(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>campus_partner.user.avatar_url</code>. 头像 Url
     */
    public String getAvatarUrl() {
        return (String) get(8);
    }

    /**
     * Setter for <code>campus_partner.user.nickname</code>. 昵称
     */
    public void setNickname(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>campus_partner.user.nickname</code>. 昵称
     */
    public String getNickname() {
        return (String) get(9);
    }

    /**
     * Setter for <code>campus_partner.user.gender</code>. 用户性别；0-男；1-女
     */
    public void setGender(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>campus_partner.user.gender</code>. 用户性别；0-男；1-女
     */
    public Integer getGender() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>campus_partner.user.auth_data</code>. 微信认证信息
     */
    public void setAuthData(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>campus_partner.user.auth_data</code>. 微信认证信息
     */
    public String getAuthData() {
        return (String) get(11);
    }

    /**
     * Setter for <code>campus_partner.user.open_id</code>. 用户 open ID
     */
    public void setOpenId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>campus_partner.user.open_id</code>. 用户 open ID
     */
    public String getOpenId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>campus_partner.user.is_authed</code>. 用户是否认证；0-否；1-是
     */
    public void setIsAuthed(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>campus_partner.user.is_authed</code>. 用户是否认证；0-否；1-是
     */
    public Integer getIsAuthed() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>campus_partner.user.auth_institution_id</code>. 用户认证机构 ID
     */
    public void setAuthInstitutionId(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>campus_partner.user.auth_institution_id</code>. 用户认证机构 ID
     */
    public String getAuthInstitutionId() {
        return (String) get(14);
    }

    /**
     * Setter for <code>campus_partner.user.auth_institution</code>. 用户认证机构名
     */
    public void setAuthInstitution(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>campus_partner.user.auth_institution</code>. 用户认证机构名
     */
    public String getAuthInstitution() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, byte[], Date, String, Integer, String, String, String, String, String, Integer, String, String, Integer, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, byte[], Date, String, Integer, String, String, String, String, String, Integer, String, String, Integer, String, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return User.USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field2() {
        return User.USER.OBJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return User.USER.AUTH_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return User.USER.AUTH_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return User.USER.AUTH_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return User.USER.QQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return User.USER.WECHAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return User.USER.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return User.USER.AVATAR_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return User.USER.NICKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return User.USER.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return User.USER.AUTH_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return User.USER.OPEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return User.USER.IS_AUTHED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return User.USER.AUTH_INSTITUTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return User.USER.AUTH_INSTITUTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value2() {
        return getObjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getAuthDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAuthId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getAuthType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getQq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWechat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAvatarUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getAuthData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getOpenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getIsAuthed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getAuthInstitutionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getAuthInstitution();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value2(byte... value) {
        setObjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value3(Date value) {
        setAuthDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value4(String value) {
        setAuthId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value5(Integer value) {
        setAuthType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value6(String value) {
        setQq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value7(String value) {
        setWechat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value8(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value9(String value) {
        setAvatarUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value10(String value) {
        setNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value11(Integer value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value12(String value) {
        setAuthData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value13(String value) {
        setOpenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value14(Integer value) {
        setIsAuthed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value15(String value) {
        setAuthInstitutionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord value16(String value) {
        setAuthInstitution(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserRecord values(Long value1, byte[] value2, Date value3, String value4, Integer value5, String value6, String value7, String value8, String value9, String value10, Integer value11, String value12, String value13, Integer value14, String value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id, byte[] objectId, Date authDatetime, String authId, Integer authType, String qq, String wechat, String phone, String avatarUrl, String nickname, Integer gender, String authData, String openId, Integer isAuthed, String authInstitutionId, String authInstitution) {
        super(User.USER);

        set(0, id);
        set(1, objectId);
        set(2, authDatetime);
        set(3, authId);
        set(4, authType);
        set(5, qq);
        set(6, wechat);
        set(7, phone);
        set(8, avatarUrl);
        set(9, nickname);
        set(10, gender);
        set(11, authData);
        set(12, openId);
        set(13, isAuthed);
        set(14, authInstitutionId);
        set(15, authInstitution);
    }
}
