/*
 * This file is generated by jOOQ.
*/
package org.campus.partner.pojo.po.mysql.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Feedback implements Serializable {

    private static final long serialVersionUID = -1762513170;

    private Long   id;
    private byte[] objectId;
    private String userId;
    private String content;
    private Date   createdDatetime;
    private Date   modifiedDatetime;

    public Feedback() {}

    public Feedback(Feedback value) {
        this.id = value.id;
        this.objectId = value.objectId;
        this.userId = value.userId;
        this.content = value.content;
        this.createdDatetime = value.createdDatetime;
        this.modifiedDatetime = value.modifiedDatetime;
    }

    public Feedback(
        Long   id,
        byte[] objectId,
        String userId,
        String content,
        Date   createdDatetime,
        Date   modifiedDatetime
    ) {
        this.id = id;
        this.objectId = objectId;
        this.userId = userId;
        this.content = content;
        this.createdDatetime = createdDatetime;
        this.modifiedDatetime = modifiedDatetime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public byte[] getObjectId() {
        return this.objectId;
    }

    public void setObjectId(byte... objectId) {
        this.objectId = objectId;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Date getCreatedDatetime() {
        return this.createdDatetime;
    }

    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    public Date getModifiedDatetime() {
        return this.modifiedDatetime;
    }

    public void setModifiedDatetime(Date modifiedDatetime) {
        this.modifiedDatetime = modifiedDatetime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Feedback (");

        sb.append(id);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(userId);
        sb.append(", ").append(content);
        sb.append(", ").append(createdDatetime);
        sb.append(", ").append(modifiedDatetime);

        sb.append(")");
        return sb.toString();
    }
}
