/*
 * This file is generated by jOOQ.
*/
package org.campus.partner.pojo.po.mysql.tables.pojos;


import java.io.Serializable;
import java.util.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Subscribe implements Serializable {

    private static final long serialVersionUID = 2090011598;

    private Long    id;
    private byte[]  objectId;
    private String  userId;
    private String  userPhone;
    private String  content;
    private String  startLocation;
    private String  endLocation;
    private Integer subscribeTag;
    private Date    subscribeEndDatetime;
    private Date    createdDatetime;
    private Date    modifiedDatetime;

    public Subscribe() {}

    public Subscribe(Subscribe value) {
        this.id = value.id;
        this.objectId = value.objectId;
        this.userId = value.userId;
        this.userPhone = value.userPhone;
        this.content = value.content;
        this.startLocation = value.startLocation;
        this.endLocation = value.endLocation;
        this.subscribeTag = value.subscribeTag;
        this.subscribeEndDatetime = value.subscribeEndDatetime;
        this.createdDatetime = value.createdDatetime;
        this.modifiedDatetime = value.modifiedDatetime;
    }

    public Subscribe(
        Long    id,
        byte[]  objectId,
        String  userId,
        String  userPhone,
        String  content,
        String  startLocation,
        String  endLocation,
        Integer subscribeTag,
        Date    subscribeEndDatetime,
        Date    createdDatetime,
        Date    modifiedDatetime
    ) {
        this.id = id;
        this.objectId = objectId;
        this.userId = userId;
        this.userPhone = userPhone;
        this.content = content;
        this.startLocation = startLocation;
        this.endLocation = endLocation;
        this.subscribeTag = subscribeTag;
        this.subscribeEndDatetime = subscribeEndDatetime;
        this.createdDatetime = createdDatetime;
        this.modifiedDatetime = modifiedDatetime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public byte[] getObjectId() {
        return this.objectId;
    }

    public void setObjectId(byte... objectId) {
        this.objectId = objectId;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserPhone() {
        return this.userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getStartLocation() {
        return this.startLocation;
    }

    public void setStartLocation(String startLocation) {
        this.startLocation = startLocation;
    }

    public String getEndLocation() {
        return this.endLocation;
    }

    public void setEndLocation(String endLocation) {
        this.endLocation = endLocation;
    }

    public Integer getSubscribeTag() {
        return this.subscribeTag;
    }

    public void setSubscribeTag(Integer subscribeTag) {
        this.subscribeTag = subscribeTag;
    }

    public Date getSubscribeEndDatetime() {
        return this.subscribeEndDatetime;
    }

    public void setSubscribeEndDatetime(Date subscribeEndDatetime) {
        this.subscribeEndDatetime = subscribeEndDatetime;
    }

    public Date getCreatedDatetime() {
        return this.createdDatetime;
    }

    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    public Date getModifiedDatetime() {
        return this.modifiedDatetime;
    }

    public void setModifiedDatetime(Date modifiedDatetime) {
        this.modifiedDatetime = modifiedDatetime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Subscribe (");

        sb.append(id);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(userId);
        sb.append(", ").append(userPhone);
        sb.append(", ").append(content);
        sb.append(", ").append(startLocation);
        sb.append(", ").append(endLocation);
        sb.append(", ").append(subscribeTag);
        sb.append(", ").append(subscribeEndDatetime);
        sb.append(", ").append(createdDatetime);
        sb.append(", ").append(modifiedDatetime);

        sb.append(")");
        return sb.toString();
    }
}
