/*
 * This file is generated by jOOQ.
*/
package org.campus.partner.pojo.po.mysql;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.campus.partner.pojo.po.mysql.tables.CompanionRoom;
import org.campus.partner.pojo.po.mysql.tables.Feedback;
import org.campus.partner.pojo.po.mysql.tables.RoomMember;
import org.campus.partner.pojo.po.mysql.tables.Subscribe;
import org.campus.partner.pojo.po.mysql.tables.User;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CampusPartner extends SchemaImpl {

    private static final long serialVersionUID = -279217115;

    /**
     * The reference instance of <code>campus_partner</code>
     */
    public static final CampusPartner CAMPUS_PARTNER = new CampusPartner();

    /**
     * The table <code>campus_partner.companion_room</code>.
     */
    public final CompanionRoom COMPANION_ROOM = org.campus.partner.pojo.po.mysql.tables.CompanionRoom.COMPANION_ROOM;

    /**
     * The table <code>campus_partner.feedback</code>.
     */
    public final Feedback FEEDBACK = org.campus.partner.pojo.po.mysql.tables.Feedback.FEEDBACK;

    /**
     * The table <code>campus_partner.room_member</code>.
     */
    public final RoomMember ROOM_MEMBER = org.campus.partner.pojo.po.mysql.tables.RoomMember.ROOM_MEMBER;

    /**
     * The table <code>campus_partner.subscribe</code>.
     */
    public final Subscribe SUBSCRIBE = org.campus.partner.pojo.po.mysql.tables.Subscribe.SUBSCRIBE;

    /**
     * The table <code>campus_partner.user</code>.
     */
    public final User USER = org.campus.partner.pojo.po.mysql.tables.User.USER;

    /**
     * No further instances allowed
     */
    private CampusPartner() {
        super("campus_partner", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            CompanionRoom.COMPANION_ROOM,
            Feedback.FEEDBACK,
            RoomMember.ROOM_MEMBER,
            Subscribe.SUBSCRIBE,
            User.USER);
    }
}
