/*
 * This file is generated by jOOQ.
*/
package org.campus.partner.pojo.po.mysql;


import javax.annotation.Generated;

import org.campus.partner.pojo.po.mysql.tables.CompanionRoom;
import org.campus.partner.pojo.po.mysql.tables.Feedback;
import org.campus.partner.pojo.po.mysql.tables.RoomMember;
import org.campus.partner.pojo.po.mysql.tables.Subscribe;
import org.campus.partner.pojo.po.mysql.tables.User;


/**
 * Convenience access to all tables in campus_partner
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>campus_partner.companion_room</code>.
     */
    public static final CompanionRoom COMPANION_ROOM = org.campus.partner.pojo.po.mysql.tables.CompanionRoom.COMPANION_ROOM;

    /**
     * The table <code>campus_partner.feedback</code>.
     */
    public static final Feedback FEEDBACK = org.campus.partner.pojo.po.mysql.tables.Feedback.FEEDBACK;

    /**
     * The table <code>campus_partner.room_member</code>.
     */
    public static final RoomMember ROOM_MEMBER = org.campus.partner.pojo.po.mysql.tables.RoomMember.ROOM_MEMBER;

    /**
     * The table <code>campus_partner.subscribe</code>.
     */
    public static final Subscribe SUBSCRIBE = org.campus.partner.pojo.po.mysql.tables.Subscribe.SUBSCRIBE;

    /**
     * The table <code>campus_partner.user</code>.
     */
    public static final User USER = org.campus.partner.pojo.po.mysql.tables.User.USER;
}
